"use client";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useLanguage } from "@/lib/i18n/LanguageContext";

const content = {
  en: {
    title: "Terms of Service",
    updated: "Last updated: March 2026",
    sections: [
      {
        heading: "1. Acceptance",
        body: "By downloading or using the Phasr app, or by visiting our website, you agree to these Terms of Service. If you do not agree, please do not use Phasr.",
      },
      {
        heading: "2. What Phasr is",
        body: "Phasr provides AI-generated training plans for runners, triathletes, and Hyrox athletes. Training plans are generated automatically based on the information you provide. They are intended as a training tool, not as a substitute for advice from a qualified coach or medical professional.",
      },
      {
        heading: "3. Health disclaimer",
        body: "Training involves physical exertion and carries inherent risks. Before starting any training programme, consult a qualified healthcare professional if you have any medical conditions or concerns. Phasr accepts no liability for injuries, illness, or other health issues that may arise from following a training plan generated by the app.",
      },
      {
        heading: "4. Your account",
        body: "You are responsible for maintaining the security of your account credentials and for all activity that occurs under your account. You must be at least 16 years old to use Phasr.",
      },
      {
        heading: "5. Free tier and paid features",
        body: "The core of Phasr is free to use. Premium features may be made available through a paid subscription. We reserve the right to change pricing, features, or availability at any time, with reasonable prior notice.",
      },
      {
        heading: "6. Acceptable use",
        body: "You agree to use Phasr only for lawful purposes and in accordance with these terms. You may not reverse-engineer, copy, or redistribute any part of the app or its content without our prior written consent.",
      },
      {
        heading: "7. Intellectual property",
        body: "All content, code, designs, and trademarks related to Phasr are owned by or licensed to us. Nothing in these terms grants you any rights to our intellectual property other than the right to use the app as described.",
      },
      {
        heading: "8. Limitation of liability",
        body: "Phasr is provided on an 'as is' and 'as available' basis, without warranties of any kind. To the fullest extent permitted by law, we exclude all liability for direct, indirect, incidental, or consequential damages arising from your use of, or inability to use, the app or website.",
      },
      {
        heading: "9. Changes to these terms",
        body: "We may update these terms at any time. We will notify you of significant changes via the app or by email. Continued use of Phasr after the effective date of changes constitutes your acceptance of the revised terms.",
      },
      {
        heading: "10. Governing law",
        body: "These terms are governed by the laws of the Netherlands. Any disputes shall be subject to the exclusive jurisdiction of the competent courts in the Netherlands.",
      },
      {
        heading: "11. Contact",
        body: "For questions about these terms, contact us at support@gophasr.com.",
      },
    ],
  },
  nl: {
    title: "Algemene voorwaarden",
    updated: "Laatste update: maart 2026",
    sections: [
      {
        heading: "1. Aanvaarding",
        body: "Door de Phasr-app te downloaden of te gebruiken, of door onze website te bezoeken, ga je akkoord met deze algemene voorwaarden. Als je hier niet mee instemt, verzoeken we je geen gebruik te maken van Phasr.",
      },
      {
        heading: "2. Wat Phasr is",
        body: "Phasr biedt AI-gegenereerde trainingsplannen voor hardlopers, triatleten en Hyrox-atleten. Trainingsplannen worden automatisch gegenereerd op basis van de informatie die je verstrekt. Ze zijn bedoeld als hulpmiddel, niet als vervanging van advies van een gekwalificeerde coach of zorgprofessional.",
      },
      {
        heading: "3. Gezondheidsdisclaimer",
        body: "Trainen brengt fysieke inspanning en inherente risico's met zich mee. Raadpleeg een arts of zorgprofessional voordat je begint met een trainingsprogramma, zeker als je medische klachten of aandoeningen hebt. Phasr aanvaardt geen aansprakelijkheid voor blessures, ziekte of andere gezondheidsklachten die kunnen voortvloeien uit het volgen van een door de app gegenereerd trainingsplan.",
      },
      {
        heading: "4. Je account",
        body: "Je bent verantwoordelijk voor het beveiligen van je inloggegevens en voor alle activiteiten die via jouw account plaatsvinden. Je moet minimaal 16 jaar oud zijn om gebruik te maken van Phasr.",
      },
      {
        heading: "5. Gratis versie en betaalde functies",
        body: "De kern van Phasr is gratis te gebruiken. Premiumfuncties kunnen beschikbaar worden gesteld via een betaald abonnement. We behouden ons het recht voor om prijzen, functies of beschikbaarheid te wijzigen, met redelijke voorafgaande kennisgeving.",
      },
      {
        heading: "6. Aanvaardbaar gebruik",
        body: "Je stemt ermee in Phasr uitsluitend te gebruiken voor rechtmatige doeleinden en in overeenstemming met deze voorwaarden. Het is niet toegestaan de app of de inhoud ervan te reverse-engineeren, te kopiëren of te verspreiden zonder onze voorafgaande schriftelijke toestemming.",
      },
      {
        heading: "7. Intellectueel eigendom",
        body: "Alle content, code, ontwerpen en handelsmerken die verband houden met Phasr zijn eigendom van of in licentie gegeven aan ons. Niets in deze voorwaarden verleent je enig recht op ons intellectueel eigendom, anders dan het recht de app te gebruiken zoals hierin beschreven.",
      },
      {
        heading: "8. Beperking van aansprakelijkheid",
        body: "Phasr wordt aangeboden 'zoals het is' en 'zoals het beschikbaar is', zonder enige garantie. Voor zover wettelijk toegestaan, sluiten wij alle aansprakelijkheid uit voor directe, indirecte, incidentele of gevolgschade die voortvloeit uit je gebruik van of het niet kunnen gebruiken van de app of website.",
      },
      {
        heading: "9. Wijzigingen in deze voorwaarden",
        body: "We kunnen deze voorwaarden op elk moment bijwerken. We informeren je over wezenlijke wijzigingen via de app of per e-mail. Voortgezet gebruik van Phasr na de ingangsdatum van wijzigingen geldt als aanvaarding van de herziene voorwaarden.",
      },
      {
        heading: "10. Toepasselijk recht",
        body: "Op deze voorwaarden is Nederlands recht van toepassing. Geschillen worden uitsluitend voorgelegd aan de bevoegde rechter in Nederland.",
      },
      {
        heading: "11. Contact",
        body: "Voor vragen over deze voorwaarden kun je contact opnemen via support@gophasr.com.",
      },
    ],
  },
};

export default function TermsPage() {
  const { locale } = useLanguage();
  const c = content[locale] ?? content.en;

  return (
    <main className="bg-navy-deeper min-h-screen">
      <Navbar />

      <section className="max-w-3xl mx-auto px-6 py-24">
        <p className="text-accent text-sm font-semibold uppercase tracking-widest mb-3">
          Legal
        </p>
        <h1 className="text-4xl sm:text-5xl font-extrabold text-white leading-tight mb-4">
          {c.title}
        </h1>
        <p className="text-white/30 text-sm mb-16">{c.updated}</p>

        <div className="space-y-12">
          {c.sections.map((section) => (
            <div key={section.heading}>
              <h2 className="text-white font-bold text-lg mb-3">
                {section.heading}
              </h2>
              <p className="text-white/60 leading-relaxed">{section.body}</p>
            </div>
          ))}
        </div>
      </section>

      <Footer />
    </main>
  );
}
